# Batrisyia Balqis , uses an appropriate escape characters and arithmetic expression
#  This code is for lab test 2 
print("Name:Ahmad Bin Abu\t\t\t\tMatric.No: MS2025123499")
print("\n")
print("*\t\t\t*")
print("**\t\t**")   
print("***\t***")
print("********")
print("***\t***")
print("**\t\t**")
print("*\t\t\t*")
print("\nThis is my")
print("\tsecond")
print("\t\tassignment")
print("I want 2x10 marks,which is 20 full marks")