import personal_data 
print(f" === Using Personal Data Module ===")
print(f'Name:{personal_data.name}')
print(f"Age:{personal_data.age}")
print(f"Height:{personal_data.height}")
print(f"Weight:{personal_data.weight} ")
print(f"Phone Number:{personal_data.phone_number} ")
print(f"Email:{personal_data.email}")
print(f"Street Address:{personal_data.street_address}")
print(f"City:{personal_data.city}")
print(f"Postcode:{personal_data.postcode}")
print(f"Name in UPPERCASE: {personal_data.name_upper}")
print(f"Name in LOWERCASE:{personal_data.name_lower}")
print(f"Name Length: {personal_data.length_name}")
print(f"City in UPPERCASE:{personal_data.city_upper}")
print(f"Full Address: {personal_data.full_address}")
print(f"Full Address Length:{personal_data.length_full_addresss}")
